@host=http://localhost:5000

// function my_schema.case_return_text(
//     _t text
// )
// returns text
POST {{host}}/api/my-schema/case-return-text
content-type: application/json

{
    "t": "ABC"
}

###

// function my_schema.hello_world()
// returns text
POST {{host}}/api/my-schema/hello-world

###

// function public.body_param_name_1p(
//     _p text
// )
// returns text
//
// comment on function public.body_param_name_1p is '
// HTTP
// body-param-name p';
POST {{host}}/api/body-param-name-1p

ABC

###

// function public.body_param_name_2p(
//     _i integer,
//     _p text
// )
// returns text
//
// comment on function public.body_param_name_2p is '
// HTTP
// body-param-name _p';
POST {{host}}/api/body-param-name-2p?i=1

XYZ

###

// function public.body_param_name_int(
//     _int integer
// )
// returns text
//
// comment on function public.body_param_name_int is '
// HTTP
// body-param-name int';
POST {{host}}/api/body-param-name-int

1

###

// function public.case_default_params(
//     _p1 integer,
//     _p2 integer DEFAULT 2,
//     _p3 integer DEFAULT 3,
//     _p4 integer DEFAULT 4
// )
// returns json
POST {{host}}/api/case-default-params
content-type: application/json

{
    "p1": 1,
    "p2": 2,
    "p3": 3,
    "p4": 4
}

###

// function public.case_get_default_params(
//     _p1 integer,
//     _p2 integer DEFAULT 2,
//     _p3 integer DEFAULT 3,
//     _p4 integer DEFAULT 4
// )
// returns json
GET {{host}}/api/case-get-default-params?p1=1&p2=2&p3=3&p4=4

###

// function public.case_get_int(
//     _i integer
// )
// returns integer
GET {{host}}/api/case-get-int?i=1

###

// function public.case_get_int_params_array(
//     _a integer[]
// )
// returns integer[]
GET {{host}}/api/case-get-int-params-array?a=1&a=2&a=3

###

// function public.case_get_multi_params1(
//     _smallint smallint,
//     _integer integer,
//     _bigint bigint,
//     _numeric numeric,
//     _text text,
//     _varchar character varying,
//     _char character,
//     _json json,
//     _jsonb jsonb,
//     _smallint_array smallint[],
//     _integer_array integer[],
//     _bigint_array bigint[],
//     _numeric_array numeric[],
//     _text_array text[],
//     _varchar_array character varying[],
//     _char_array character[],
//     _json_array json[],
//     _jsonb_array jsonb[]
// )
// returns json
GET {{host}}/api/case-get-multi-params1?smallint=1&integer=2&bigint=3&numeric=4&text=XYZ&varchar=IJK&char=ABC&json=%7B%7D&jsonb=%7B%7D&smallintArray=10&smallintArray=11&smallintArray=12&integerArray=11&integerArray=12&integerArray=13&bigintArray=12&bigintArray=13&bigintArray=14&numericArray=13&numericArray=14&numericArray=15&textArray=XYZ&textArray=IJK&textArray=ABC&varcharArray=IJK&varcharArray=ABC&varcharArray=XYZ&charArray=ABC&charArray=XYZ&charArray=IJK&jsonArray=%7B%7D&jsonArray=%7B%7D&jsonArray=%7B%7D&jsonbArray=%7B%7D&jsonbArray=%7B%7D&jsonbArray=%7B%7D

###

// function public.case_get_multi_params2(
//     _real real,
//     _double double precision,
//     _jsonpath jsonpath,
//     _timestamp timestamp without time zone,
//     _timestamptz timestamp with time zone,
//     _date date,
//     _time time without time zone,
//     _timetz time with time zone,
//     _interval interval,
//     _bool boolean,
//     _uuid uuid,
//     _varbit bit varying,
//     _bit varbit,
//     _inet inet,
//     _macaddr macaddr,
//     _bytea bytea
// )
// returns json
GET {{host}}/api/case-get-multi-params2?real=1.2&double=2.3&jsonpath=%24.user.addresses%5B0%5D.city&timestamp=2024-04-04T03%3A03%3A03.00&timestamptz=2024-05-05T04%3A04%3A04.00&date=2024-06-06&time=06%3A06%3A0&timetz=07%3A07%3A0%2B01%3A00&interval=8%20minutes%209%20seconds&bool=true&uuid=00000000-0000-0000-0000-000000000000&varbit=101&bit=010&inet=192.168.5.13&macaddr=00-B0-D0-63-C2-26&bytea=%5C%5CxDEADBEEF

###

// function public.case_get_overload()
// returns text
GET {{host}}/api/case-get-overload

###

// function public.case_get_overload(
//     _i integer
// )
// returns text
GET {{host}}/api/case-get-overload?i=1

###

// function public.case_get_overload(
//     _i integer,
//     _t text
// )
// returns text
GET {{host}}/api/case-get-overload?i=1&t=XYZ

###

// function public.case_get_overload(
//     _i integer,
//     _t text,
//     _b boolean
// )
// returns text
GET {{host}}/api/case-get-overload?i=1&t=XYZ&b=false

###

// function public.case_get_text_params_array(
//     _a text[]
// )
// returns text[]
GET {{host}}/api/case-get-text-params-array?a=ABC&a=XYZ&a=IJK

###

// function public.case_get_unnamed_int(
//      integer
// )
// returns integer
GET {{host}}/api/case-get-unnamed-int?$1=1

###

// function public.case_jsonpath_param(
//     _jsonpath jsonpath
// )
// returns text
POST {{host}}/api/case-jsonpath-param
content-type: application/json

{
    "jsonpath": "$.user.addresses[0].city"
}

###

// function public.case_multi_params1(
//     _smallint smallint,
//     _integer integer,
//     _bigint bigint,
//     _numeric numeric,
//     _text text,
//     _varchar character varying,
//     _char character,
//     _json json,
//     _jsonb jsonb,
//     _smallint_array smallint[],
//     _integer_array integer[],
//     _bigint_array bigint[],
//     _numeric_array numeric[],
//     _text_array text[],
//     _varchar_array character varying[],
//     _char_array character[],
//     _json_array json[],
//     _jsonb_array jsonb[]
// )
// returns json
POST {{host}}/api/case-multi-params1
content-type: application/json

{
    "smallint": 1,
    "integer": 2,
    "bigint": 3,
    "numeric": 4,
    "text": "XYZ",
    "varchar": "IJK",
    "char": "ABC",
    "json": {},
    "jsonb": {},
    "smallintArray": [10, 11, 12],
    "integerArray": [11, 12, 13],
    "bigintArray": [12, 13, 14],
    "numericArray": [13, 14, 15],
    "textArray": ["XYZ", "IJK", "ABC"],
    "varcharArray": ["IJK", "ABC", "XYZ"],
    "charArray": ["ABC", "XYZ", "IJK"],
    "jsonArray": [{}, {}, {}],
    "jsonbArray": [{}, {}, {}]
}

###

// function public.case_multi_params2(
//     _real real,
//     _double double precision,
//     _jsonpath jsonpath,
//     _timestamp timestamp without time zone,
//     _timestamptz timestamp with time zone,
//     _date date,
//     _time time without time zone,
//     _timetz time with time zone,
//     _interval interval,
//     _bool boolean,
//     _uuid uuid,
//     _varbit bit varying,
//     _bit varbit,
//     _inet inet,
//     _macaddr macaddr,
//     _bytea bytea
// )
// returns json
POST {{host}}/api/case-multi-params2
content-type: application/json

{
    "real": 1.2,
    "double": 2.3,
    "jsonpath": "$.user.addresses[0].city",
    "timestamp": "2024-04-04T03:03:03.00",
    "timestamptz": "2024-05-05T04:04:04.00",
    "date": "2024-06-06",
    "time": "06:06:0",
    "timetz": "07:07:0+01:00",
    "interval": "8 minutes 9 seconds",
    "bool": true,
    "uuid": "00000000-0000-0000-0000-000000000000",
    "varbit": "101",
    "bit": "010",
    "inet": "192.168.5.13",
    "macaddr": "00-B0-D0-63-C2-26",
    "bytea": "\\xDEADBEEF"
}

###

// function public.case_overload()
// returns text
POST {{host}}/api/case-overload

###

// function public.case_overload(
//     _i integer
// )
// returns text
POST {{host}}/api/case-overload
content-type: application/json

{
    "i": 1
}

###

// function public.case_overload(
//     _i integer,
//     _t text
// )
// returns text
POST {{host}}/api/case-overload
content-type: application/json

{
    "i": 1,
    "t": "XYZ"
}

###

// function public.case_overload(
//     _i integer,
//     _t text,
//     _b boolean
// )
// returns text
POST {{host}}/api/case-overload
content-type: application/json

{
    "i": 1,
    "t": "XYZ",
    "b": false
}

###

// function public.case_return_array_edge_cases()
// returns text[]
POST {{host}}/api/case-return-array-edge-cases

###

// function public.case_return_bool_array()
// returns boolean[]
POST {{host}}/api/case-return-bool-array

###

// function public.case_return_int(
//     _i integer
// )
// returns integer
POST {{host}}/api/case-return-int
content-type: application/json

{
    "i": 1
}

###

// function public.case_return_int_array()
// returns integer[]
POST {{host}}/api/case-return-int-array

###

// function public.case_return_int_array_with_null()
// returns integer[]
POST {{host}}/api/case-return-int-array-with-null

###

// function public.case_return_int_params_array(
//     _a integer[]
// )
// returns integer[]
POST {{host}}/api/case-return-int-params-array
content-type: application/json

{
    "a": [1, 2, 3]
}

###

// function public.case_return_json(
//     _json json
// )
// returns json
POST {{host}}/api/case-return-json
content-type: application/json

{
    "json": {}
}

###

// function public.case_return_setof_bool()
// returns setof boolean
POST {{host}}/api/case-return-setof-bool

###

// function public.case_return_setof_bool_array()
// returns setof boolean[]
POST {{host}}/api/case-return-setof-bool-array

###

// function public.case_return_setof_int()
// returns setof integer
POST {{host}}/api/case-return-setof-int

###

// function public.case_return_setof_int_array()
// returns setof integer[]
POST {{host}}/api/case-return-setof-int-array

###

// function public.case_return_setof_json()
// returns setof json
POST {{host}}/api/case-return-setof-json

###

// function public.case_return_setof_text()
// returns setof text
POST {{host}}/api/case-return-setof-text

###

// function public.case_return_setof_text_array()
// returns setof text[]
POST {{host}}/api/case-return-setof-text-array

###

// function public.case_return_table1()
// returns table(
//     int_field integer,
//     text_field text,
//     bool_field boolean,
//     int_array integer[],
//     text_array text[],
//     bool_array boolean[]
// )
POST {{host}}/api/case-return-table1

###

// function public.case_return_table2()
// returns table(
//     "real" real,
//     double double precision,
//     jsonpath jsonpath,
//     "timestamp" timestamp without time zone,
//     timestamptz timestamp with time zone,
//     date date,
//     "time" time without time zone,
//     timetz time with time zone,
//     "interval" interval,
//     uuid uuid,
//     varbit bit varying,
//     "bit" varbit,
//     inet inet,
//     macaddr macaddr,
//     bytea bytea
// )
POST {{host}}/api/case-return-table2

###

// function public.case_return_text(
//     _t text
// )
// returns text
POST {{host}}/api/case-return-text
content-type: application/json

{
    "t": "ABC"
}

###

// function public.case_return_text_array()
// returns text[]
POST {{host}}/api/case-return-text-array

###

// function public.case_return_text_params_array(
//     _a text[]
// )
// returns text[]
POST {{host}}/api/case-return-text-params-array
content-type: application/json

{
    "a": ["ABC", "XYZ", "IJK"]
}

###

// function public.case_return_unnamed_int(
//      integer
// )
// returns integer
POST {{host}}/api/case-return-unnamed-int
content-type: application/json

{
    "$1": 1
}

###

// function public.case_single_default_params(
//     _p text DEFAULT 'xyz'::text
// )
// returns text
POST {{host}}/api/case-single-default-params
content-type: application/json

{
    "p": "ABC"
}

###

// function public.case_void()
// returns void
POST {{host}}/api/case-void

###

// function public.comment_authorize1()
// returns text
//
// comment on function public.comment_authorize1 is 'HTTP
// Authorize';
POST {{host}}/api/comment-authorize1

###

// function public.comment_authorize2()
// returns text
//
// comment on function public.comment_authorize2 is 'HTTP
// RequiresAuthorization';
POST {{host}}/api/comment-authorize2

###

// function public.comment_authorize3()
// returns text
//
// comment on function public.comment_authorize3 is '
// Authorize';
POST {{host}}/api/comment-authorize3

###

// function public.comment_authorize4()
// returns text
//
// comment on function public.comment_authorize4 is 'Authorize
// HTTP';
POST {{host}}/api/comment-authorize4

###

// function public.comment_get_param_type_json1(
//     _t text
// )
// returns text
//
// comment on function public.comment_get_param_type_json1 is '
// HTTP
// RequestParamType BodyJson';
GET {{host}}/api/comment-get-param-type-json1
content-type: application/json

{
    "t": "ABC"
}

###

// function public.comment_get_param_type_json2(
//     _t text
// )
// returns text
//
// comment on function public.comment_get_param_type_json2 is '
// HTTP
// ParamType Json';
GET {{host}}/api/comment-get-param-type-json2
content-type: application/json

{
    "t": "ABC"
}

###

// function public.comment_param_type_query1(
//     _t text
// )
// returns text
//
// comment on function public.comment_param_type_query1 is '
// HTTP
// RequestParamType QueryString';
POST {{host}}/api/comment-param-type-query1?t=ABC

###

// function public.comment_param_type_query2(
//     _t text
// )
// returns text
//
// comment on function public.comment_param_type_query2 is '
// HTTP
// ParamType Query';
POST {{host}}/api/comment-param-type-query2?t=ABC

###

// function public.comment_response_headers()
// returns text
//
// comment on function public.comment_response_headers is '
// HTTP
// Content-Type: application/json
// CustomHeader: test
// MultiValueCustomHeader: test1
// MultiValueCustomHeader: test2
// cache-control: no-store';
POST {{host}}/api/comment-response-headers

###

// function public.comment_verb_test1()
// returns text
//
// comment on function public.comment_verb_test1 is 'HTTP GET
GET {{host}}/api/comment-verb-test1

###

// function public.comment_verb_test2()
// returns text
//
// comment on function public.comment_verb_test2 is 'This is some comment.
// Some other comment.
// HTTP GET
// And again some other comment.';
GET {{host}}/api/comment-verb-test2

###

// function public.comment_verb_test3()
// returns text
//
// comment on function public.comment_verb_test3 is 'HTTP GET custom_url_from_comment
GET {{host}}/custom_url_from_comment

###

// function public.comment_wrong_verb()
// returns text
//
// comment on function public.comment_wrong_verb is 'HTTP wrong-verb
POST {{host}}/api/comment-wrong-verb

###

// function public.ending_slash()
// returns text
POST {{host}}/api/ending-slash

###

// function public.get_csv_data()
// returns table(
//     id integer,
//     name text,
//     date timestamp without time zone,
//     status boolean
// )
GET {{host}}/api/get-csv-data

###

// function public.get_none_existing_params(
//     _p1 integer,
//     _p2 integer
// )
// returns text
GET {{host}}/api/get-none-existing-params?p1=1&p2=2

###

// function public.get_proc_test_tbl()
// returns text
GET {{host}}/api/get-proc-test-tbl

###

// function public.get_req_headers_context()
// returns text
//
// comment on function public.get_req_headers_context is '
// HTTP
// RequestHeaders Context';
GET {{host}}/api/get-req-headers-context

###

// function public.get_req_headers_ignore()
// returns text
GET {{host}}/api/get-req-headers-ignore

###

// function public.get_req_headers_param_not_default(
//     _not_default text
// )
// returns text
//
// comment on function public.get_req_headers_param_not_default is '
// HTTP
// request-headers parameter
// request-headers-parameter-name _not_default';
GET {{host}}/api/get-req-headers-param-not-default?notDefault=ABC

###

// function public.get_req_headers_parameter1(
//     _headers text DEFAULT NULL::text
// )
// returns text
//
// comment on function public.get_req_headers_parameter1 is '
// HTTP
// request-headers parameter';
GET {{host}}/api/get-req-headers-parameter1?headers=ABC

###

// function public.get_req_headers_parameter2(
//     headers text DEFAULT NULL::text
// )
// returns text
//
// comment on function public.get_req_headers_parameter2 is '
// HTTP
// request-headers parameter';
GET {{host}}/api/get-req-headers-parameter2?headers=ABC

###

// function public.get_req_headers_parameter3(
//     h text DEFAULT NULL::text
// )
// returns text
//
// comment on function public.get_req_headers_parameter3 is '
// HTTP
// request-headers parameter
// request-headers-parameter-name h';
GET {{host}}/api/get-req-headers-parameter3?h=ABC

###

// function public.get_test_records()
// returns setof record
GET {{host}}/api/get-test-records

###

// function public.get_test_table()
// returns table(
//     id integer,
//     name text
// )
GET {{host}}/api/get-test-table

###

// function public.get_timestamp()
// returns timestamp without time zone
GET {{host}}/api/get-timestamp

###

// function public.get_timestamp_array()
// returns timestamp without time zone[]
GET {{host}}/api/get-timestamp-array

###

// function public.get_timestamp_setof()
// returns setof timestamp without time zone
GET {{host}}/api/get-timestamp-setof

###

// function public.get_timestamp_table()
// returns table(
//     ts timestamp without time zone
// )
GET {{host}}/api/get-timestamp-table

###

// function public.hello_world()
// returns text
POST {{host}}/api/hello-world

###

// function public.hello_world_html()
// returns text
//
// comment on function public.hello_world_html is '
// HTTP GET
// Content-Type: text/html';
GET {{host}}/api/hello-world-html

###

// function public.immutable_func()
// returns text
GET {{host}}/api/immutable-func

###

// function public.post_none_existing_params(
//     _p1 integer,
//     _p2 integer
// )
// returns text
POST {{host}}/api/post-none-existing-params
content-type: application/json

{
    "p1": 1,
    "p2": 2
}

###

// function public.req_headers_param_not_default(
//     _not_default text
// )
// returns text
//
// comment on function public.req_headers_param_not_default is '
// HTTP
// request-headers parameter
// request-headers-parameter-name _not_default';
POST {{host}}/api/req-headers-param-not-default
content-type: application/json

{
    "notDefault": "ABC"
}

###

// function public.req_headers_parameter1(
//     _headers text DEFAULT NULL::text
// )
// returns text
//
// comment on function public.req_headers_parameter1 is '
// HTTP
// request_headers parameter';
POST {{host}}/api/req-headers-parameter1
content-type: application/json

{
    "headers": "ABC"
}

###

// function public.req_headers_parameter2(
//     headers text DEFAULT NULL::text
// )
// returns text
//
// comment on function public.req_headers_parameter2 is '
// HTTP
// request_headers parameter';
POST {{host}}/api/req-headers-parameter2
content-type: application/json

{
    "headers": "ABC"
}

###

// function public.req_headers_parameter3(
//     h text DEFAULT NULL::text
// )
// returns text
//
// comment on function public.req_headers_parameter3 is '
// HTTP
// request-headers parameter
// request_headers_parameter_name h';
POST {{host}}/api/req-headers-parameter3
content-type: application/json

{
    "h": "ABC"
}

###

// function public.returns_null_on_null_input_function(
//     _p1 integer,
//     _p2 integer
// )
// returns text
POST {{host}}/api/returns-null-on-null-input-function
content-type: application/json

{
    "p1": 1,
    "p2": 2
}

###

// function public."select"(
//     "group" integer,
//     "order" integer
// )
// returns table(
//     "from" integer,
//     "join" integer
// )
POST {{host}}/api/select
content-type: application/json

{
    "group": 1,
    "order": 2
}

###

// function public.stable_func()
// returns text
GET {{host}}/api/stable-func

###

// function public.strict_function(
//     _p1 integer,
//     _p2 integer
// )
// returns text
POST {{host}}/api/strict-function
content-type: application/json

{
    "p1": 1,
    "p2": 2
}

###

// function public.variadic_param_plus_one(
//     v integer[]
// )
// returns integer[]
POST {{host}}/api/variadic-param-plus-one
content-type: application/json

{
    "v": [1, 2, 3]
}

###

// function public.volatile_func()
// returns text
POST {{host}}/api/volatile-func

###

// procedure public.proc_test(
//     _t text
// )
// returns void
POST {{host}}/api/proc-test
content-type: application/json

{
    "t": "ABC"
}

###

// select public.crud_delete1
GET {{host}}/api/crud-delete1?id=1&name=XYZ

###

// insert into public.crud_delete1
PUT {{host}}/api/crud-delete1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_delete1
// returning
//     id, name
PUT {{host}}/api/crud-delete1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_delete1
DELETE {{host}}/api/crud-delete1?id=1&name=XYZ

###

// delete from public.crud_delete1
// returning
//     id, name
DELETE {{host}}/api/crud-delete1/returning?id=1&name=XYZ

###

// select public.crud_delete2
GET {{host}}/api/crud-delete2?id=1&name=XYZ

###

// insert into public.crud_delete2
PUT {{host}}/api/crud-delete2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_delete2
// returning
//     id, name
PUT {{host}}/api/crud-delete2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_delete2
DELETE {{host}}/api/crud-delete2?id=1&name=XYZ

###

// delete from public.crud_delete2
// returning
//     id, name
DELETE {{host}}/api/crud-delete2/returning?id=1&name=XYZ

###

// select public.crud_insert1
GET {{host}}/api/crud-insert1?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// insert into public.crud_insert1
PUT {{host}}/api/crud-insert1
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_insert1
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-insert1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// delete from public.crud_insert1
DELETE {{host}}/api/crud-insert1?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// delete from public.crud_insert1
// returning
//     id, name, some_date, status
DELETE {{host}}/api/crud-insert1/returning?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// select public.crud_insert2
GET {{host}}/api/crud-insert2?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// insert into public.crud_insert2
PUT {{host}}/api/crud-insert2
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_insert2
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-insert2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// delete from public.crud_insert2
DELETE {{host}}/api/crud-insert2?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// delete from public.crud_insert2
// returning
//     id, name, some_date, status
DELETE {{host}}/api/crud-insert2/returning?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// select public.crud_insert3
GET {{host}}/api/crud-insert3?id=1&name=XYZ

###

// insert into public.crud_insert3
PUT {{host}}/api/crud-insert3
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert3
// returning
//     id, name
PUT {{host}}/api/crud-insert3/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert3
DELETE {{host}}/api/crud-insert3?id=1&name=XYZ

###

// delete from public.crud_insert3
// returning
//     id, name
DELETE {{host}}/api/crud-insert3/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_nothing_returning_test1
GET {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_nothing_returning_test1
POST {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_nothing_returning_test1
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test1
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test1
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test1
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test1
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_nothing_returning_test1
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_nothing_returning_test1
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test1/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_nothing_returning_test2
GET {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_nothing_returning_test2
POST {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_nothing_returning_test2
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test2
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test2
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test2
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test2
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_nothing_returning_test2
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_nothing_returning_test2
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test2/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_nothing_returning_test3
GET {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3?id1=1&id2=2&name=IJK

###

// update public.crud_insert_on_conflict_do_nothing_returning_test3
POST {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// update public.crud_insert_on_conflict_do_nothing_returning_test3
// returning
//     id1, id2, name
POST {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test3
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test3
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test3
// on conflict (id1, id2) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/on-conflict-do-nothing
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test3
// on conflict (id1, id2) do nothing
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/on-conflict-do-nothing/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/on-conflict-do-update
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_returning_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/on-conflict-do-update/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// delete from public.crud_insert_on_conflict_do_nothing_returning_test3
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3?id1=1&id2=2&name=IJK

###

// delete from public.crud_insert_on_conflict_do_nothing_returning_test3
// returning
//     id1, id2, name
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-returning-test3/returning?id1=1&id2=2&name=IJK

###

// select public.crud_insert_on_conflict_do_nothing_test1
GET {{host}}/api/crud-insert-on-conflict-do-nothing-test1?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_nothing_test1
POST {{host}}/api/crud-insert-on-conflict-do-nothing-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_nothing_test1
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-nothing-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test1
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test1
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test1
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test1/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test1
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test1/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test1/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test1/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_nothing_test1
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-test1?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_nothing_test1
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-test1/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_nothing_test2
GET {{host}}/api/crud-insert-on-conflict-do-nothing-test2?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_nothing_test2
POST {{host}}/api/crud-insert-on-conflict-do-nothing-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_nothing_test2
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-nothing-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test2
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test2
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test2
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test2/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test2
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test2/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test2/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test2/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_nothing_test2
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-test2?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_nothing_test2
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-test2/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_nothing_test3
GET {{host}}/api/crud-insert-on-conflict-do-nothing-test3?id1=1&id2=2&name=IJK

###

// update public.crud_insert_on_conflict_do_nothing_test3
POST {{host}}/api/crud-insert-on-conflict-do-nothing-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// update public.crud_insert_on_conflict_do_nothing_test3
// returning
//     id1, id2, name
POST {{host}}/api/crud-insert-on-conflict-do-nothing-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test3
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test3
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test3
// on conflict (id1, id2) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test3/on-conflict-do-nothing
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test3
// on conflict (id1, id2) do nothing
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test3/on-conflict-do-nothing/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test3/on-conflict-do-update
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_nothing_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-nothing-test3/on-conflict-do-update/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// delete from public.crud_insert_on_conflict_do_nothing_test3
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-test3?id1=1&id2=2&name=IJK

###

// delete from public.crud_insert_on_conflict_do_nothing_test3
// returning
//     id1, id2, name
DELETE {{host}}/api/crud-insert-on-conflict-do-nothing-test3/returning?id1=1&id2=2&name=IJK

###

// select public.crud_insert_on_conflict_do_update_returning_test1
GET {{host}}/api/crud-insert-on-conflict-do-update-returning-test1?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_update_returning_test1
POST {{host}}/api/crud-insert-on-conflict-do-update-returning-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_update_returning_test1
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test1
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test1
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test1
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test1
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_update_returning_test1
DELETE {{host}}/api/crud-insert-on-conflict-do-update-returning-test1?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_update_returning_test1
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-update-returning-test1/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_update_returning_test2
GET {{host}}/api/crud-insert-on-conflict-do-update-returning-test2?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_update_returning_test2
POST {{host}}/api/crud-insert-on-conflict-do-update-returning-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_update_returning_test2
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test2
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test2
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test2
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test2
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_update_returning_test2
DELETE {{host}}/api/crud-insert-on-conflict-do-update-returning-test2?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_update_returning_test2
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-update-returning-test2/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_update_returning_test3
GET {{host}}/api/crud-insert-on-conflict-do-update-returning-test3?id1=1&id2=2&name=IJK

###

// update public.crud_insert_on_conflict_do_update_returning_test3
POST {{host}}/api/crud-insert-on-conflict-do-update-returning-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// update public.crud_insert_on_conflict_do_update_returning_test3
// returning
//     id1, id2, name
POST {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test3
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test3
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test3
// on conflict (id1, id2) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/on-conflict-do-nothing
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test3
// on conflict (id1, id2) do nothing
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/on-conflict-do-nothing/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/on-conflict-do-update
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_returning_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/on-conflict-do-update/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// delete from public.crud_insert_on_conflict_do_update_returning_test3
DELETE {{host}}/api/crud-insert-on-conflict-do-update-returning-test3?id1=1&id2=2&name=IJK

###

// delete from public.crud_insert_on_conflict_do_update_returning_test3
// returning
//     id1, id2, name
DELETE {{host}}/api/crud-insert-on-conflict-do-update-returning-test3/returning?id1=1&id2=2&name=IJK

###

// select public.crud_insert_on_conflict_do_update_test1
GET {{host}}/api/crud-insert-on-conflict-do-update-test1?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_update_test1
POST {{host}}/api/crud-insert-on-conflict-do-update-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_update_test1
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-update-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test1
PUT {{host}}/api/crud-insert-on-conflict-do-update-test1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test1
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test1
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-update-test1/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test1
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test1/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test1/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test1
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test1/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_update_test1
DELETE {{host}}/api/crud-insert-on-conflict-do-update-test1?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_update_test1
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-update-test1/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_update_test2
GET {{host}}/api/crud-insert-on-conflict-do-update-test2?id=1&name=XYZ

###

// update public.crud_insert_on_conflict_do_update_test2
POST {{host}}/api/crud-insert-on-conflict-do-update-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// update public.crud_insert_on_conflict_do_update_test2
// returning
//     id, name
POST {{host}}/api/crud-insert-on-conflict-do-update-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test2
PUT {{host}}/api/crud-insert-on-conflict-do-update-test2
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test2
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test2/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test2
// on conflict (id) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-update-test2/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test2
// on conflict (id) do nothing
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test2/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test2/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_on_conflict_do_update_test2
// on conflict (id) 
// do update set 
//     name = excluded.name
// returning
//     id, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test2/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_on_conflict_do_update_test2
DELETE {{host}}/api/crud-insert-on-conflict-do-update-test2?id=1&name=XYZ

###

// delete from public.crud_insert_on_conflict_do_update_test2
// returning
//     id, name
DELETE {{host}}/api/crud-insert-on-conflict-do-update-test2/returning?id=1&name=XYZ

###

// select public.crud_insert_on_conflict_do_update_test3
GET {{host}}/api/crud-insert-on-conflict-do-update-test3?id1=1&id2=2&name=IJK

###

// update public.crud_insert_on_conflict_do_update_test3
POST {{host}}/api/crud-insert-on-conflict-do-update-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// update public.crud_insert_on_conflict_do_update_test3
// returning
//     id1, id2, name
POST {{host}}/api/crud-insert-on-conflict-do-update-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_test3
PUT {{host}}/api/crud-insert-on-conflict-do-update-test3
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_test3
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test3/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_test3
// on conflict (id1, id2) do nothing
PUT {{host}}/api/crud-insert-on-conflict-do-update-test3/on-conflict-do-nothing
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_test3
// on conflict (id1, id2) do nothing
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test3/on-conflict-do-nothing/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test3/on-conflict-do-update
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// insert into public.crud_insert_on_conflict_do_update_test3
// on conflict (id1, id2) 
// do update set 
//     name = excluded.name
// returning
//     id1, id2, name
PUT {{host}}/api/crud-insert-on-conflict-do-update-test3/on-conflict-do-update/returning
content-type: application/json

{
    "id1": 1,
    "id2": 2,
    "name": "IJK"
}

###

// delete from public.crud_insert_on_conflict_do_update_test3
DELETE {{host}}/api/crud-insert-on-conflict-do-update-test3?id1=1&id2=2&name=IJK

###

// delete from public.crud_insert_on_conflict_do_update_test3
// returning
//     id1, id2, name
DELETE {{host}}/api/crud-insert-on-conflict-do-update-test3/returning?id1=1&id2=2&name=IJK

###

// select public.crud_insert_returning1
GET {{host}}/api/crud-insert-returning1?id=1&name=XYZ

###

// insert into public.crud_insert_returning1
PUT {{host}}/api/crud-insert-returning1
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.crud_insert_returning1
// returning
//     id, name
PUT {{host}}/api/crud-insert-returning1/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.crud_insert_returning1
DELETE {{host}}/api/crud-insert-returning1?id=1&name=XYZ

###

// delete from public.crud_insert_returning1
// returning
//     id, name
DELETE {{host}}/api/crud-insert-returning1/returning?id=1&name=XYZ

###

// select public.crud_select_tests
GET {{host}}/api/crud-select-tests?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// insert into public.crud_select_tests
PUT {{host}}/api/crud-select-tests
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_select_tests
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-select-tests/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// delete from public.crud_select_tests
DELETE {{host}}/api/crud-select-tests?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// delete from public.crud_select_tests
// returning
//     id, name, some_date, status
DELETE {{host}}/api/crud-select-tests/returning?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// select public.crud_update_returning_tests
GET {{host}}/api/crud-update-returning-tests?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// update public.crud_update_returning_tests
POST {{host}}/api/crud-update-returning-tests
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// update public.crud_update_returning_tests
// returning
//     id, name, some_date, status
POST {{host}}/api/crud-update-returning-tests/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_returning_tests
PUT {{host}}/api/crud-update-returning-tests
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_returning_tests
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-update-returning-tests/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_returning_tests
// on conflict (id) do nothing
PUT {{host}}/api/crud-update-returning-tests/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_returning_tests
// on conflict (id) do nothing
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-update-returning-tests/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_returning_tests
// on conflict (id) 
// do update set 
//     name = excluded.name, 
//     some_date = excluded.some_date, 
//     status = excluded.status
PUT {{host}}/api/crud-update-returning-tests/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_returning_tests
// on conflict (id) 
// do update set 
//     name = excluded.name, 
//     some_date = excluded.some_date, 
//     status = excluded.status
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-update-returning-tests/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// delete from public.crud_update_returning_tests
DELETE {{host}}/api/crud-update-returning-tests?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// delete from public.crud_update_returning_tests
// returning
//     id, name, some_date, status
DELETE {{host}}/api/crud-update-returning-tests/returning?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// select public.crud_update_tests
GET {{host}}/api/crud-update-tests?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// update public.crud_update_tests
POST {{host}}/api/crud-update-tests
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// update public.crud_update_tests
// returning
//     id, name, some_date, status
POST {{host}}/api/crud-update-tests/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_tests
PUT {{host}}/api/crud-update-tests
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_tests
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-update-tests/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_tests
// on conflict (id) do nothing
PUT {{host}}/api/crud-update-tests/on-conflict-do-nothing
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_tests
// on conflict (id) do nothing
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-update-tests/on-conflict-do-nothing/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_tests
// on conflict (id) 
// do update set 
//     name = excluded.name, 
//     some_date = excluded.some_date, 
//     status = excluded.status
PUT {{host}}/api/crud-update-tests/on-conflict-do-update
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// insert into public.crud_update_tests
// on conflict (id) 
// do update set 
//     name = excluded.name, 
//     some_date = excluded.some_date, 
//     status = excluded.status
// returning
//     id, name, some_date, status
PUT {{host}}/api/crud-update-tests/on-conflict-do-update/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "someDate": "2024-03-03",
    "status": true
}

###

// delete from public.crud_update_tests
DELETE {{host}}/api/crud-update-tests?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// delete from public.crud_update_tests
// returning
//     id, name, some_date, status
DELETE {{host}}/api/crud-update-tests/returning?id=1&name=XYZ&someDate=2024-03-03&status=true

###

// select public.proc_test_tbl
GET {{host}}/api/proc-test-tbl?i=1&t=XYZ

###

// insert into public.proc_test_tbl
PUT {{host}}/api/proc-test-tbl
content-type: application/json

{
    "i": 1,
    "t": "XYZ"
}

###

// insert into public.proc_test_tbl
// returning
//     i, t
PUT {{host}}/api/proc-test-tbl/returning
content-type: application/json

{
    "i": 1,
    "t": "XYZ"
}

###

// delete from public.proc_test_tbl
DELETE {{host}}/api/proc-test-tbl?i=1&t=XYZ

###

// delete from public.proc_test_tbl
// returning
//     i, t
DELETE {{host}}/api/proc-test-tbl/returning?i=1&t=XYZ

###

// select public.test_table
GET {{host}}/api/test-table?id=1&name=XYZ

###

// insert into public.test_table
PUT {{host}}/api/test-table
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// insert into public.test_table
// returning
//     id, name
PUT {{host}}/api/test-table/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ"
}

###

// delete from public.test_table
DELETE {{host}}/api/test-table?id=1&name=XYZ

###

// delete from public.test_table
// returning
//     id, name
DELETE {{host}}/api/test-table/returning?id=1&name=XYZ

###

